// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLkxXaNisWW0eE1t1GUk6-AGWrcHvl-0',
    appId: '1:887453963667:web:28a304de944478c200c466',
    messagingSenderId: '887453963667',
    projectId: 'task-ealim',
    authDomain: 'task-ealim.firebaseapp.com',
    storageBucket: 'task-ealim.appspot.com',
    measurementId: 'G-BCHZ0BQL90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5titjoCHtziesL6fte8Cf5G-AZJYFdJY',
    appId: '1:887453963667:android:ce73ddc5802b66e800c466',
    messagingSenderId: '887453963667',
    projectId: 'task-ealim',
    storageBucket: 'task-ealim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWAhDxcAXCk4vsnDAvA9bZ_ZwgpktgDs',
    appId: '1:887453963667:ios:7be2e91b695065d100c466',
    messagingSenderId: '887453963667',
    projectId: 'task-ealim',
    storageBucket: 'task-ealim.appspot.com',
    iosBundleId: 'com.example.tasksEalim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWAhDxcAXCk4vsnDAvA9bZ_ZwgpktgDs',
    appId: '1:887453963667:ios:48b2e0fb9dce4bbf00c466',
    messagingSenderId: '887453963667',
    projectId: 'task-ealim',
    storageBucket: 'task-ealim.appspot.com',
    iosBundleId: 'com.example.tasksEalim.RunnerTests',
  );
}
